// ============================================================
// Foodie-AD — Mock 数据 (10+ 阿布扎比真实区域餐厅)
// ============================================================

import { Restaurant } from '@/types';

export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Nan Bei Restaurant',
    nameZh: '南北餐厅',
    description: 'Legendary Chinese restaurant hidden in the heart of Abu Dhabi. The handmade dumplings will make you forget you\'re 6000km from home.',
    descriptionZh: '藏在阿布扎比市中心的传奇中餐厅，手工饺子让你忘记自己离家6000公里。',
    address: 'Abu Dhabi Mall, Tourist Club Area',
    area: 'Tourist Club Area',
    category: 'chinese',
    vibes: ['weekend-gaming', 'broke-but-tasty'],
    lat: 24.4936,
    lng: 54.3815,
    rating: 4.5,
    funnyScore: 5,
    coverImage: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
      'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    ],
    funnyQuote: 'The dumplings hit different at 2am. Absolutely zero regrets.',
    funnyQuoteZh: '凌晨两点的饺子有一种神奇的魔力，吃完没有任何后悔。',
    priceLevel: 2,
    status: 'approved',
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Sajway',
    nameZh: 'Sajway 肉夹馍',
    description: 'The undisputed king of shawarma in Abu Dhabi. Queue at 11pm? Normal. Worth it? Absolutely.',
    descriptionZh: '阿布扎比沙瓦尔马界的无冕之王。凌晨11点还在排队？正常现象。值得吗？绝对的。',
    address: 'Electra Street, Downtown Abu Dhabi',
    area: 'Downtown',
    category: 'arabic',
    vibes: ['midnight-fuel', 'broke-but-tasty', 'quick-bite'],
    lat: 24.4899,
    lng: 54.3578,
    rating: 4.8,
    funnyScore: 4,
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    ],
    funnyQuote: 'Scientists have yet to explain why shawarma tastes 300% better after midnight.',
    funnyQuoteZh: '科学家们至今无法解释为何沙瓦尔马在午夜之后会美味300%。',
    priceLevel: 1,
    status: 'approved',
    createdAt: '2025-02-10T08:00:00Z',
  },
  {
    id: '3',
    name: 'Reem Al Bawadi',
    nameZh: '里姆巴瓦迪',
    description: 'Authentic Emirati cuisine with portions so generous you\'ll need a nap after. Business lunches? Yes. First dates? Risky (sleep mode may activate).',
    descriptionZh: '正宗阿联酋美食，份量大到你需要饭后小睡。商务午餐？可以。第一次约会？有风险（可能触发睡眠模式）。',
    address: 'Reem Island, Abu Dhabi',
    area: 'Reem Island',
    category: 'arabic',
    vibes: ['reem-island', 'business-flex', 'weekend-gaming'],
    lat: 24.5010,
    lng: 54.4000,
    rating: 4.3,
    funnyScore: 3,
    coverImage: 'https://images.unsplash.com/photo-1542574271-7f3b92e6c821?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1542574271-7f3b92e6c821?w=800&q=80',
    ],
    funnyQuote: 'The hummus alone could win a Nobel Peace Prize.',
    funnyQuoteZh: '光是那碗鹰嘴豆泥就足以获诺贝尔和平奖。',
    priceLevel: 2,
    status: 'approved',
    createdAt: '2025-02-20T12:00:00Z',
  },
  {
    id: '4',
    name: 'Zuma Abu Dhabi',
    nameZh: 'Zuma 日本料理',
    description: 'Upscale Japanese with views that will make your Instagram followers question whether you actually live in Abu Dhabi.',
    descriptionZh: '高档日本料理，景色让你的Instagram粉丝质疑你是否真的住在阿布扎比。',
    address: 'Nation Towers, Corniche',
    area: 'Corniche',
    category: 'japanese',
    vibes: ['business-flex', 'spicy-challenge'],
    lat: 24.4607,
    lng: 54.3274,
    rating: 4.6,
    funnyScore: 2,
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    ],
    funnyQuote: 'Dress code: pretend you belong here. You do. Probably.',
    funnyQuoteZh: '着装要求：假装你属于这里。你确实属于，大概。',
    priceLevel: 4,
    status: 'approved',
    createdAt: '2025-03-01T18:00:00Z',
  },
  {
    id: '5',
    name: 'Rangoli',
    nameZh: 'Rangoli 印度餐厅',
    description: 'The butter chicken here is so good it should be illegal. Mild for wimps, spicy for warriors. No in-between.',
    descriptionZh: '这里的黄油鸡好吃到应该被列为非法。温和版给懦夫，辣版给勇士。没有中间选项。',
    address: 'Al Khalidiyah, Abu Dhabi',
    area: 'Khalidiyah',
    category: 'indian',
    vibes: ['spicy-challenge', 'broke-but-tasty', 'weekend-gaming'],
    lat: 24.4711,
    lng: 54.3457,
    rating: 4.4,
    funnyScore: 4,
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    ],
    funnyQuote: 'The naan bread is so fluffy, it has its own cloud certification.',
    funnyQuoteZh: '烤饼蓬松到已经获得了云朵认证。',
    priceLevel: 2,
    status: 'approved',
    createdAt: '2025-03-15T11:00:00Z',
  },
  {
    id: '6',
    name: 'Jones the Grocer',
    nameZh: 'Jones the Grocer',
    description: 'Fancy brunch spot where your avocado toast costs more than your Didi ride home. Worth every fils.',
    descriptionZh: '高档早午餐圣地，你的牛油果吐司比打车回家还贵。每一分钱都值。',
    address: 'Abu Dhabi Global Market Square, Al Maryah Island',
    area: 'Al Maryah Island',
    category: 'cafe',
    vibes: ['health-freak', 'business-flex'],
    lat: 24.4954,
    lng: 54.3897,
    rating: 4.2,
    funnyScore: 3,
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    ],
    funnyQuote: 'The WiFi password is "avocadotoast" and we respect that energy.',
    funnyQuoteZh: 'WiFi密码是"avocadotoast"，我们尊重这种气质。',
    priceLevel: 3,
    status: 'approved',
    createdAt: '2025-04-01T09:00:00Z',
  },
  {
    id: '7',
    name: 'Shake Shack Abu Dhabi',
    nameZh: 'Shake Shack 汉堡',
    description: 'Yes it\'s a chain. Yes we\'re including it. The ShackBurger is a diplomatic solution to any argument.',
    descriptionZh: '是的，这是连锁店。是的，我们还是把它列进来了。ShackBurger是任何争吵的外交解决方案。',
    address: 'Yas Mall, Yas Island',
    area: 'Yas Island',
    category: 'fast-food',
    vibes: ['quick-bite', 'weekend-gaming', 'broke-but-tasty'],
    lat: 24.4944,
    lng: 54.6081,
    rating: 4.0,
    funnyScore: 3,
    coverImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    ],
    funnyQuote: 'Single? No. I\'m in a committed relationship with a double ShackBurger.',
    funnyQuoteZh: '单身吗？不，我和一个双层ShackBurger正处于热恋中。',
    priceLevel: 2,
    status: 'approved',
    createdAt: '2025-04-10T14:00:00Z',
  },
  {
    id: '8',
    name: 'Sontaya',
    nameZh: 'Sontaya 泰国餐厅',
    description: 'Thai food with Corniche views. The pad thai here will haunt your dreams (in the best way).',
    descriptionZh: '科尼切海滨景观泰国餐厅。这里的炒河粉会入侵你的梦境（是好那种）。',
    address: 'Park Rotana, Abu Dhabi',
    area: 'Tourist Club Area',
    category: 'western',
    vibes: ['business-flex', 'reem-island'],
    lat: 24.4878,
    lng: 54.3790,
    rating: 4.3,
    funnyScore: 3,
    coverImage: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800&q=80',
    ],
    funnyQuote: 'The tom yum soup is 90% broth, 10% therapy session.',
    funnyQuoteZh: '冬荫功汤里90%是汤底，10%是心理治疗。',
    priceLevel: 3,
    status: 'approved',
    createdAt: '2025-04-20T19:00:00Z',
  },
  {
    id: '9',
    name: 'Al Arish Restaurant',
    nameZh: '阿里什餐厅',
    description: 'The most authentic Emirati experience outside of a royal palace. Luqaimat dessert should be classified as a controlled substance.',
    descriptionZh: '皇家宫殿之外最正宗的阿联酋体验。Luqaimat甜点应该被列为管控物质。',
    address: 'Khalifa Park, Abu Dhabi',
    area: 'Khalifa City',
    category: 'arabic',
    vibes: ['business-flex', 'weekend-gaming'],
    lat: 24.4424,
    lng: 54.3714,
    rating: 4.5,
    funnyScore: 4,
    coverImage: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    ],
    funnyQuote: 'Eating here makes you feel like you just signed a peace treaty.',
    funnyQuoteZh: '在这里吃饭让你感觉自己刚刚签署了一份和平条约。',
    priceLevel: 2,
    status: 'approved',
    createdAt: '2025-05-01T12:00:00Z',
  },
  {
    id: '10',
    name: 'Catch 22 — AVOID ⚠️',
    nameZh: 'Catch 22 — 避雷 ⚠️',
    description: 'We tried it so you don\'t have to. Overpriced, underwhelming, and the wifi was "5G" which actually meant 5 Ghosts and no signal.',
    descriptionZh: '我们替你踩了这个雷。价格虚高，品质垫底，WiFi所谓的"5G"其实是5个鬼，没有信号。',
    address: 'Somewhere on the Corniche',
    area: 'Corniche',
    category: 'western',
    vibes: [],
    lat: 24.4555,
    lng: 54.3300,
    rating: 1.8,
    funnyScore: 5,
    coverImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    ],
    funnyQuote: '💩 We have given this restaurant a 💩 rating. Avoid unless you enjoy disappointment as a hobby.',
    funnyQuoteZh: '💩 本店荣获💩评级。除非你把失望当爱好，否则请绕道而行。',
    priceLevel: 3,
    status: 'approved',
    createdAt: '2025-05-15T20:00:00Z',
  },
];

export const getRestaurantById = (id: string): Restaurant | undefined => {
  return mockRestaurants.find((r) => r.id === id);
};

export const getApprovedRestaurants = (): Restaurant[] => {
  return mockRestaurants.filter((r) => r.status === 'approved');
};

export const filterByVibe = (restaurants: Restaurant[], vibe: string | null): Restaurant[] => {
  if (!vibe) return restaurants;
  return restaurants.filter((r) => r.vibes.includes(vibe as any));
};
